import './globals.css';
import { Inter } from 'next/font/google';

import SupabaseProvider from './supabase-provider';

const inter = Inter({ subsets: [ 'latin' ] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

const RootLayout = ({ children }: {
  children: React.ReactNode
}) => {
	return (
		<html
			lang="fr-fr"
			style={ { height: '100%' } }
		>
			<body
				className={ `${ inter.className } bg-gray-50` }
				style={ { height: '100%' } }
			>
				<SupabaseProvider>{ children }</SupabaseProvider>
			</body>
		</html>
	);
};

export default RootLayout;
